server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/drugstore?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret-key: ${JWT_SECRET}
  expiration: 86400000

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD}

app:
  name: Drugstore
  url: ${APP_URL:http://localhost:3000}

vnpay:
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  tmn-code: ${VNPAY_TMN_CODE:2Y0P3N8L}
  hash-secret: ${VNPAY_HASH_SECRET:1BX5VZOVDP8G19NJCYVC4OZW2V5XXLZG}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8081/api/orders/vnpay-return}
  ip-addr: ${VNPAY_IP_ADDR:127.0.0.1}

aws:
  s3:
    bucketName: ${AWS_S3_BUCKET_NAME}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    endpointUrl: ${AWS_S3_ENDPOINT_URL}